title: Meilin Shi
position: PhD Student
affiliation: University of Vienna
email: meilin.shi@univie.ac.at
google_scholar: https://scholar.google.com/citations?user=t831HF0AAAAJ&hl=en&authuser=1
github_link: https://github.com/meilinshi
linkedin: https://www.linkedin.com/in/meilin-shi-373a98120/
avatar: ./assets/img/profile.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
